apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2018-05-31T11:12:41Z'
  generation: 2
  labels:
    app: app
  name: app
  namespace: keycloak
  resourceVersion: '18759'
  selfLink: /apis/apps.openshift.io/v1/namespaces/keycloak/deploymentconfigs/app
  uid: 88d25899-64c3-11e8-96ba-fec082c3eecb
spec:
  replicas: 1
  selector:
    deploymentconfig: app
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
        deploymentconfig: app
    spec:
      containers:
        - image: >-
            172.30.1.1:5000/keycloak/app@sha256:6f36fd10f33070fed10ce634e366db77ddb4f2a2379723117d4b36338f9bec3d
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - app
        from:
          kind: ImageStreamTag
          name: 'app:latest'
          namespace: keycloak
        lastTriggeredImage: >-
          172.30.1.1:5000/keycloak/app@sha256:6f36fd10f33070fed10ce634e366db77ddb4f2a2379723117d4b36338f9bec3d
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-05-31T11:12:53Z'
      lastUpdateTime: '2018-05-31T11:12:53Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-05-31T11:12:54Z'
      lastUpdateTime: '2018-05-31T11:12:54Z'
      message: replication controller "app-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1

